paths:
  contracts: contracts/
  artifacts: artifacts/

networks:
  default: localnet
  localnet:
    id: 61999
    url: http://127.0.0.1:4010/api

  studionet:
    id: 61999
    url: https://studio.genlayer.com/api
