import { serve } from "@hono/node-server";
import app from "./index.js";
import { Database, ExpiringStore } from "./lib/db.js";
import type { Env } from "./lib/env.js";
import { pollOnce } from "./indexer/poll.js";
const db = new Database(process.env.DATABASE_URL ?? "");
const env: Env = { DB: db, NONCES: new ExpiringStore(db), GENLAYER_NETWORK: process.env.GENLAYER_NETWORK ?? "studionet", GENLAYER_RPC_URL: process.env.GENLAYER_RPC_URL ?? "https://studio.genlayer.com/api", CONTRACT_ADDRESS: process.env.CONTRACT_ADDRESS, GENLAYER_CHAIN_ID: process.env.GENLAYER_CHAIN_ID, GENLAYER_RPC_MAX_REQUESTS_PER_DAY: process.env.GENLAYER_RPC_MAX_REQUESTS_PER_DAY, UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL, UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN, JWT_SECRET: process.env.JWT_SECRET ?? "", INTERNAL_SECRET: process.env.INTERNAL_SECRET };
const port = Number(process.env.PORT ?? 8080); serve({ fetch: (request) => app.fetch(request, env), port });
const interval = setInterval(() => pollOnce(env).catch((err) => console.error("[indexer]", err)), 120_000);
process.on("SIGTERM", async () => { clearInterval(interval); await db.close(); process.exit(0); });
